#! /usr/bin/env python

import roslib
roslib.load_manifest('mavpro')
import rospy
import actionlib

from mavpro.msg import TakeoffAction, TakeoffGoal

if __name__ == '__main__':
	rospy.init_node('takeoff_client')
	client = actionlib.SimpleActionClient('takeoff', TakeoffAction)
	rospy.logwarn("Starting takeoff_client...")

	client.wait_for_server()

	goal = TakeoffGoal()
	# Fill in the goal here
	goal.altitude = rospy.get_param('~alt', 2)


	client.send_goal(goal)
	rospy.logwarn("Sent takeoff goal with altitude %4.2f...", goal.altitude)

	client.wait_for_result(rospy.Duration.from_sec(600.0))